import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

SOURCES=Glob('lexlib/*.cxx') + Glob('lexers/*.cxx') + Glob('src/*.cxx') + Glob('awtk/*.cxx');

env.Library(os.path.join(BIN_DIR, 'scintilla'), SOURCES)
